model = "gpt-5.2"
model_reasoning_effort = "high"
web_search = "live"
suppress_unstable_features_warning = true

[notice]
hide_full_access_warning = true

[notice.model_migrations]
"gpt-5.1-codex-mini" = "gpt-5.2-codex"
"gpt-5.2" = "gpt-5.2-codex"
"gpt-5.1-codex-max" = "gpt-5.2-codex"

[mcp_servers.notion]
url = "https://mcp.notion.com/mcp"
startup_timeout_sec = 30

[features]
experimental_windows_sandbox = true
elevated_windows_sandbox = true
unified_exec = true
shell_snapshot = true
steer = true
powershell_utf8 = true
undo = true
child_agents_md = true





















