model = "gpt-5.3-codex"
model_reasoning_effort = "xhigh"

[mcp_servers]

[mcp_servers.MCP_DOCKER]
command = "docker.exe"
args = ["mcp", "gateway", "run"]

[mcp_servers.openaiDeveloperDocs]
url = "https://developers.openai.com/mcp"

[mcp_servers.context7]
url = "https://mcp.context7.com/mcp"
bearer_token_env_var = "CONTEXT7_API_KEY"

[mcp_servers.github]
command = "npx"
args = ["-y", "@modelcontextprotocol/server-github"]

[mcp_servers.sequentialThinking]
command = "npx"
args = ["-y", "@modelcontextprotocol/server-sequential-thinking"]

[mcp_servers.filesystem]
command = "npx"
args = ["-y", "@modelcontextprotocol/server-filesystem", 'C:\Users\monke']

[mcp_servers.memory]
command = "npx"
args = ["-y", "@modelcontextprotocol/server-memory"]

[mcp_servers.lsp-ts]
command = "npx"
args = ["-y", "github:erans/lsp-mcp", "--config", 'C:\Users\monke\.codex\mcp\lsp-servers.yaml', "--lsp", "typescript", "--workspace", 'C:\Users\monke']

[mcp_servers.lsp-py]
command = "npx"
args = ["-y", "github:erans/lsp-mcp", "--config", 'C:\Users\monke\.codex\mcp\lsp-servers.yaml', "--lsp", "python", "--workspace", 'C:\Users\monke']

[mcp_servers.lsp-json]
command = "npx"
args = ["-y", "github:erans/lsp-mcp", "--config", 'C:\Users\monke\.codex\mcp\lsp-servers.yaml', "--lsp", "json", "--workspace", 'C:\Users\monke']

[mcp_servers.lsp-bash]
command = "npx"
args = ["-y", "github:erans/lsp-mcp", "--config", 'C:\Users\monke\.codex\mcp\lsp-servers.yaml', "--lsp", "bash", "--workspace", 'C:\Users\monke']

[mcp_servers.lsp-yaml]
command = "npx"
args = ["-y", "github:erans/lsp-mcp", "--config", 'C:\Users\monke\.codex\mcp\lsp-servers.yaml', "--lsp", "yaml", "--workspace", 'C:\Users\monke']

[notice]
hide_full_access_warning = true

[projects]
[projects.'\\?\C:\Users\monke\jacks_happy_bots']
trust_level = 'trusted'


[windows]
sandbox = 'elevated'
